import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import AboutPage from './about'
import DesktopHeader from '../components/DesktopHeader/DesktopHeader'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Agence Vigile Africa | Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-ava.ico" />
      </Head>

      <main className={styles.main}>
        <DesktopHeader />



        <h2>Home Page</h2>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
